version: "3.2"

networks:
  integration-test-expenses:

services:
  it_tests:
    environment:
      DATABASE_URL: postgresql://postgres:password@db/postgres?sslmode=disable
    build:
      context: .
      dockerfile: ./Dockerfile.test
    volumes:
      - .:/go/src/target
    depends_on:
      - db
    networks:
      - integration-test-expenses
  db:
    image: postgres:12.12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    restart: on-failure
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    networks:
      - integration-test-expenses
