services:
  postgresql:
    image: postgres:15.1
    volumes:
      - type: bind
        source: ./database
        target: /docker-entrypoint-initdb.d/
        read_only: true
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
